version: 0.2

phases:
  build:
    commands:
      # Run Docker container on EC2
      - docker run -d -p 4000:4000 -v /var/lib/docker/overlay2/6506d49a74b2d71c63bb3cc25df21ab1678442a5655d227d85fbdbbb7fd22c4e/merged:/app goal_tracker_project_image:latest
