version: 0.2

phases:
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y nodejs npm

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t goal_tracker_final_project_img .

  post_build:
    commands:
      - echo "Saving Docker image locally..."
      - docker save -o goal_tracker_final_project_img.tar goal_tracker_final_project_img
      - chmod 400 goal-tracker-instance2-key.pem
      - echo "Copying Docker image to EC2 instance..."
      - scp -v -o StrictHostKeyChecking=no -i goal-tracker-instance2-key.pem goal_tracker_final_project_img.tar ubuntu@3.81.67.114:~/
      - echo "Connecting to EC2 instance and loading Docker image..."
      - ssh -i goal-tracker-instance2-key.pem ubuntu@3.81.67.114 "docker load -i goal_tracker_final_project_img.tar"

artifacts:
  files: imagedefinitions.json